"""Run the four required demonstration scenarios end to end.

    python scripts/demo.py                      # print to the console
    python scripts/demo.py --write docs/SAMPLE_QA.md

Scenario A  RAG only        - knowledge-base question, retrieval, grounded answer
Scenario B  MCP only        - weather and currency questions routed to MCP tools
Scenario C  RAG + MCP       - weather-aware itinerary and a budget-aware itinerary
Scenario D  Conversation    - a question followed by a context-dependent follow-up
Scenario E  Safety          - a question the knowledge base cannot answer
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from travel_assistant.assistant import Answer, TravelAssistant  # noqa: E402

SCENARIOS: list[tuple[str, str, list[str]]] = [
    (
        "A. RAG — grounded destination knowledge",
        "Answered only from the indexed knowledge base; no MCP tool is called.",
        [
            "What are the must-visit attractions in Singapore?",
            "How can a tourist travel around Singapore?",
        ],
    ),
    (
        "B. MCP — live information through tools",
        "Routed to the MCP server; the knowledge base is not used for these facts.",
        [
            "What is the weather forecast in Singapore for the next three days?",
            "Convert INR 50,000 to SGD.",
        ],
    ),
    (
        "C. RAG + MCP — combined response",
        "Knowledge base supplies the places, MCP tools supply the live data.",
        [
            "Create a three-day Singapore itinerary for next week and adjust it according to "
            "the weather forecast.",
            "I have a budget of INR 60,000. Convert it to SGD and suggest a three-day itinerary.",
        ],
    ),
    (
        "D. Conversation — retained context and preferences",
        "The follow-ups contain no destination or budget; both come from the conversation.",
        [
            "I am travelling with my kids for three days and my budget is INR 80,000.",
            "Suggest activities for us.",
            "What indoor options do we have if it rains?",
            "And how much is that budget in SGD?",
        ],
    ),
    (
        "E. Missing knowledge and tool failures — no fabrication",
        "The knowledge base has no data for the first question; the second asks for a currency "
        "the rate service does not publish.",
        [
            "What are the 2026 ticket prices for the Singapore Grand Prix paddock club?",
            "Convert 100 ZWL to SGD.",
        ],
    ),
]


def render(answer: Answer) -> str:
    lines = [f"**Question:** {answer.question}", ""]
    lines += [f"**Route:** {answer.intent.label} · **Generator:** {answer.generator}", ""]
    lines += ["**Answer:**", "", answer.text, ""]

    if answer.citations:
        lines.append("**Knowledge-base sources used:**")
        for citation in answer.citations:
            section = f" — {citation['section']}" if citation["section"] else ""
            url = f" · {citation['url']}" if citation["url"] else ""
            lines.append(
                f"- {citation['title']}{section} (similarity {citation['score']}){url}"
            )
        lines.append("")

    if answer.tool_calls:
        lines.append("**MCP tool calls:**")
        for call in answer.tool_calls:
            state = "succeeded" if call.ok else f"failed — {call.error}"
            lines.append(f"- `{call.tool}` arguments `{call.arguments}` → {state}")
        lines.append("")

    if answer.notes:
        lines.append("**Notes:**")
        lines += [f"- {note}" for note in answer.notes]
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the demonstration scenarios.")
    parser.add_argument("--write", type=Path, help="write the transcript to a Markdown file")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(levelname)s %(name)s: %(message)s",
    )

    assistant = TravelAssistant()
    status = assistant.status()
    out: list[str] = [
        "# Sample questions and application responses",
        "",
        "Generated by `python scripts/demo.py --write docs/SAMPLE_QA.md`. Every answer below is "
        "real application output captured during that run.",
        "",
        f"- Run at: {datetime.now(UTC).isoformat(timespec='seconds')}",
        f"- Destination: {status['destination']}",
        f"- Embedding model: `{status['knowledge_base']['embedding_model']}`",
        f"- Knowledge-base index present: {status['knowledge_base']['index_available']}",
        f"- MCP server connected: {status['mcp']['connected']}"
        + (
            f" (tools: {', '.join(tool['name'] for tool in status['mcp']['tools'])})"
            if status["mcp"]["connected"]
            else f" — {status['mcp']['error']}"
        ),
        f"- Answer generator: {status['generator']['label']}",
        "",
    ]

    for heading, description, questions in SCENARIOS:
        out += [f"## {heading}", "", f"_{description}_", ""]
        assistant.reset()  # each scenario starts from a clean conversation
        for question in questions:
            print(f"[{heading}] {question}")
            out += [render(assistant.ask(question)), "---", ""]

    document = "\n".join(out).rstrip() + "\n"
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(document, encoding="utf-8")
        print(f"\nWrote {args.write}")
    else:
        print()
        print(document)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
